<html>
<body>

<?
error_reporting( E_ALL );
//$ierror_reporting = error_reporting();
//print "$ierror_reporting<br>";

require ("library.php.inc");
//print "include library.php.inc!<br>";

list ( $Description, $Products ) = readFiles( 'HPE-Network.csv' );
//print_r ( $Products );

$Products = multOut ( $Products );
//print_r ( $Products );

//.. Write base parameters to session
setSession ( $Description, $Products );

//.. tableOut( $Description, $Products ); //.. Äî ëó÷øèõ âðåìåí :)

//.. Select search parameters

list ( $pLevel, $pNumPorts, $pSreda, $pPorts, $pPOEbudget, $pMAC, $pProizv, $pPropusk) = collectParameters ( );

/* TEST 
print_r ( $pLevel );
print_r ( $pNumPorts );
print_r ( $pSreda );
print_r ( $pPOEbudget );
print_r ( $pMAC );
print_r ( $pProizv );
print_r ( $pPropusk );
*/

zaprosParameters( $pLevel, $pNumPorts, $pSreda, $pPorts, $pPOEbudget, $pMAC, $pProizv, $pPropusk);

?>

</BODY>
</HTML>
